linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/prasenjit/openid-golang
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  revive:
    confidence: 0.8

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - whitespace
    - exportloopref
    - goconst
    - gocyclo
    - revive
  disable:
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gocyclo
    - path: cmd/
      linters:
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - ui/admin/node_modules
  skip-files:
    - ".*\\.pb\\.go$"
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
