# golangci-lint v2.x configuration
version: '2'

linters:
  enable:
    # Default linters (always enabled)
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple, stylecheck, etc.
    - unused
    # Additional linters
    - misspell
    - unconvert
    - whitespace
    - goconst
    - gocyclo
    - revive

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
