# Docker Compose for OpenID Connect Server
# Provides easy setup for development and testing

version: '3.8'

services:
  openid-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: openid-server:latest
    container_name: openid-server
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      # Optional: MongoDB connection (if not set, uses JSON file storage)
      # - MONGODB_URI=mongodb://admin:changeme@mongodb:27017
      # - MONGODB_DATABASE=openid
    volumes:
      # Mount data directory for persistent configuration and storage
      # Contains: data/config.json (configuration + JWT keys)
      #          data/openid.json (users, clients, tokens - JSON mode only)
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - openid-network
    depends_on:
      - mongodb
    profiles:
      - json-storage

  # OpenID server with MongoDB backend
  openid-server-mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    image: openid-server:latest
    container_name: openid-server-mongodb
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://admin:changeme@mongodb:27017
      - MONGODB_DATABASE=openid
    volumes:
      # Only need data directory for config store (data/config.json)
      # User/client/token data is stored in MongoDB
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - openid-network
    depends_on:
      - mongodb
    profiles:
      - with-mongodb

  # Optional: MongoDB for production storage
  mongodb:
    image: mongo:7
    container_name: openid-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=changeme
      - MONGO_INITDB_DATABASE=openid
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    restart: unless-stopped
    networks:
      - openid-network
    profiles:
      - with-mongodb

networks:
  openid-network:
    driver: bridge

volumes:
  mongodb-data:
  mongodb-config:
