#!/bin/bash

# Documentation Overview Generator
# This script shows the structure of the documentation

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     OpenID Connect Identity Server - Documentation         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 All documentation is organized in the docs/ folder"
echo ""
echo "Root Directory:"
echo "├── README.md                          Main project overview"
echo "├── STRUCTURE.md                       Project structure guide"
echo "├── setup.sh                           Setup script ⭐"
echo "├── test.sh                            Quick test script ⭐"
echo "└── Makefile                           Build commands"
echo ""
echo "Documentation (docs/):"
echo "├── INDEX.md                           📚 Documentation hub"
echo "├── GETTING_STARTED.md                 ⭐ Start here!"
echo "├── QUICKSTART.md                      Quick reference"
echo "├── PROJECT_SUMMARY.md                 What was built"
echo "├── IMPLEMENTATION.md                  Technical details"
echo "├── API.md                             API reference"
echo "├── ARCHITECTURE.md                    Architecture & diagrams"
echo "└── TESTING.md                         Testing guide"
echo ""
echo "Code Structure:"
echo "├── cmd/server/                        Application entry point"
echo "├── internal/                          Private application code"
echo "│   ├── config/                        Configuration"
echo "│   ├── crypto/                        JWT, PKCE, bcrypt"
echo "│   ├── handlers/                      HTTP handlers"
echo "│   ├── middleware/                    HTTP middleware"
echo "│   ├── models/                        Data models"
echo "│   └── storage/                       Database layer"
echo "├── scripts/                           Utility scripts"
echo "└── examples/                          Example applications"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📖 Reading Guide:"
echo ""
echo "1. New Users:"
echo "   → Start with docs/GETTING_STARTED.md"
echo ""
echo "2. Experienced Developers:"
echo "   → Jump to docs/QUICKSTART.md"
echo ""
echo "3. API Integration:"
echo "   → Reference docs/API.md"
echo ""
echo "4. Understanding the Code:"
echo "   → Read docs/IMPLEMENTATION.md"
echo "   → Study docs/ARCHITECTURE.md"
echo ""
echo "5. Testing:"
echo "   → Follow docs/TESTING.md"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚀 Quick Commands:"
echo ""
echo "  ./setup.sh                           # Complete setup"
echo "  go run scripts/seed.go               # Create test data"
echo "  ./test.sh                            # Start server"
echo "  go run examples/test-client.go       # Test OAuth flow"
echo ""
echo "════════════════════════════════════════════════════════════"
